### PR TITLE
Add HA Addon

### PR DESCRIPTION
**Pull request by foxdalas**
It's a preview of the HA Addon:

GitHub Actions (Linter, Builder)
Configuration: ini file -> YAML
If you want to check it out, please add the https://github.com/foxdalas/daikin_mqtt repository to your Home Assistant.

Work still in progress

### CODE REVIEW

**Review by chrisp250 — APPROVED** [review]
Thank you for the updates and extra features @foxdalas 

I'll merge your commits but haven't had a chance to test them. I'm hoping you can help if any issues show up.

Cheers

**Comment by chrisp250** [comment]
Actually it won't let me merge the changes while they are draft. I have approved them though.

Please let me know when you are ready and I'll merge them. Thank you for your work @foxdalas!

Christian

**Comment by foxdalas** [comment]
> Actually it won't let me merge the changes while they are draft. I have approved them though.
> 
> 
> 
> Please let me know when you are ready and I'll merge them. Thank you for your work @foxdalas!
> 
> 
> 
> Christian

@chrisp250 give me a couple days for testing. 

I will try to migrate to GitHub registry and I need to fix config interface. 

Thank you for the project.

**Comment by foxdalas** [comment]
@chrisp250 please fix conflicts. I don't have access

**Review by chrisp250 — APPROVED** [review]

**Comment by foxdalas** [comment]
@chrisp250 The base branch does not allow updates

**Comment by chrisp250** [comment]
@foxdalas merge is done. Are you ready for me to release a new version?

**Pull request merged**
